import React, { useState, useEffect, useMemo } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { Todo, Priority, FilterStatus, SortOption } from './types';
import * as storageService from './services/storageService';
import TodoForm from './components/TodoForm';
import TodoItem from './components/TodoItem';
import Stats from './components/Stats';
import { ListFilter, ArrowUpDown, Info } from 'lucide-react';

const App: React.FC = () => {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [filter, setFilter] = useState<FilterStatus>('ALL');
  const [sortBy, setSortBy] = useState<SortOption>('DATE_ADDED');
  const [isLoaded, setIsLoaded] = useState(false);

  // Load initial data
  useEffect(() => {
    const loadedTodos = storageService.loadTodos();
    setTodos(loadedTodos);
    setIsLoaded(true);
  }, []);

  // Save on change
  useEffect(() => {
    if (isLoaded) {
      storageService.saveTodos(todos);
    }
  }, [todos, isLoaded]);

  const handleAddTodo = (newTodoData: Omit<Todo, 'id' | 'createdAt' | 'isCompleted'>) => {
    const newTodo: Todo = {
      id: uuidv4(),
      createdAt: Date.now(),
      isCompleted: false,
      ...newTodoData
    };

    setTodos(prev => [newTodo, ...prev]);
    return true;
  };

  const handleToggleTodo = (id: string) => {
    setTodos(prev => prev.map(t => 
      t.id === id ? { ...t, isCompleted: !t.isCompleted } : t
    ));
  };

  const handleDeleteTodo = (id: string) => {
    setTodos(prev => prev.filter(t => t.id !== id));
  };

  const handleAddSubtasks = (subtasks: string[]) => {
    const newTodos = subtasks.map(title => ({
      id: uuidv4(),
      createdAt: Date.now(),
      isCompleted: false,
      title: title.substring(0, 60), 
      priority: Priority.MEDIUM,
      description: 'Generated by AI',
      estimatedHours: 0
    }));
    
    setTodos(prev => [...newTodos, ...prev]);
  };

  const clearCompleted = () => {
    setTodos(prev => prev.filter(t => !t.isCompleted));
  };

  const filteredAndSortedTodos = useMemo(() => {
    let result = [...todos];

    // Filter
    if (filter === 'ACTIVE') {
      result = result.filter(t => !t.isCompleted);
    } else if (filter === 'COMPLETED') {
      result = result.filter(t => t.isCompleted);
    }

    // Sort
    result.sort((a, b) => {
      if (sortBy === 'PRIORITY') {
        const priorityWeight = { [Priority.HIGH]: 3, [Priority.MEDIUM]: 2, [Priority.LOW]: 1 };
        return priorityWeight[b.priority] - priorityWeight[a.priority];
      } else if (sortBy === 'DUE_DATE') {
        // Safe access in case of undefined due dates (sort them last)
        const dateA = a.dueDate ? new Date(a.dueDate).getTime() : Infinity;
        const dateB = b.dueDate ? new Date(b.dueDate).getTime() : Infinity;
        return dateA - dateB;
      } else if (sortBy === 'EFFORT') {
        return (b.estimatedHours || 0) - (a.estimatedHours || 0);
      } else {
        // Date Added (Default: Newest first)
        return b.createdAt - a.createdAt;
      }
    });

    return result;
  }, [todos, filter, sortBy]);

  return (
    <div className="min-h-screen bg-slate-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto space-y-6">
        
        {/* Header */}
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight">
            Task Master
          </h1>
          <p className="text-slate-500 max-w-lg mx-auto">
            Stay organized and boost your productivity.
          </p>
        </div>

        <Stats todos={todos} />

        <TodoForm onAdd={handleAddTodo} />

        {/* Controls */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-4 py-2 border-b border-slate-200">
          <div className="flex items-center gap-2">
            <ListFilter className="w-4 h-4 text-slate-400" />
            <select 
              value={filter}
              onChange={(e) => setFilter(e.target.value as FilterStatus)}
              className="bg-transparent text-sm font-medium text-slate-600 focus:outline-none cursor-pointer"
            >
              <option value="ALL">All Tasks</option>
              <option value="ACTIVE">Active</option>
              <option value="COMPLETED">Completed</option>
            </select>
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <ArrowUpDown className="w-4 h-4 text-slate-400" />
              <select 
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value as SortOption)}
                className="bg-transparent text-sm font-medium text-slate-600 focus:outline-none cursor-pointer"
              >
                <option value="DATE_ADDED">Date Added</option>
                <option value="DUE_DATE">Due Date</option>
                <option value="PRIORITY">Priority</option>
                <option value="EFFORT">Effort (Hrs)</option>
              </select>
            </div>
            
            {todos.some(t => t.isCompleted) && (
              <button 
                onClick={clearCompleted}
                className="text-xs text-red-500 hover:text-red-700 hover:underline"
              >
                Clear Completed
              </button>
            )}
          </div>
        </div>

        {/* List */}
        <div className="space-y-3">
          {filteredAndSortedTodos.length === 0 ? (
            <div className="text-center py-12 bg-white rounded-xl border border-dashed border-slate-300">
              <Info className="w-12 h-12 text-slate-300 mx-auto mb-3" />
              <p className="text-slate-500 font-medium">No tasks found</p>
              <p className="text-sm text-slate-400">Add a new task to get started</p>
            </div>
          ) : (
            filteredAndSortedTodos.map(todo => (
              <TodoItem 
                key={todo.id} 
                todo={todo} 
                onToggle={handleToggleTodo} 
                onDelete={handleDeleteTodo}
                onAddSubtasks={handleAddSubtasks}
              />
            ))
          )}
        </div>
        
        <footer className="text-center text-xs text-slate-400 mt-12">
           <p>&copy; {new Date().getFullYear()} Task Master. All rights reserved.</p>
        </footer>
      </div>
    </div>
  );
};

export default App;